name: turkish_dictionary
description: Turkish dictionary.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State Management
  provider: ^6.0.3

  # Network
  dio: ^4.0.6
  connectivity_plus: ^2.3.9

  # Database
  hive_flutter: ^1.1.0

  # Navigation
  auto_route: ^5.0.1

  # Localization
  easy_localization: ^3.0.1

  # Animation
  animations: ^2.0.4

  # Utitilities
  kartal: ^2.4.3
  flutter_svg: ^1.1.5
  shimmer: ^2.0.0
  webview_flutter: ^3.0.4
  flutter_tts: ^3.5.3

  # JSON
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/data/
    - assets/translations/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/Regular.otf
          weight: 400
        - asset: assets/fonts/Medium.otf
          weight: 500
        - asset: assets/fonts/MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Semibold.otf
          weight: 600
        - asset: assets/fonts/Bold.otf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/ic_turkce_sozluk_app.png"
